name: Test

on:
  push:
  workflow_dispatch:

jobs:

  test:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # Attempt to generate as many of them as possible
      matrix:
        os:
          - macos-14
          - macos-12
          - ubuntu-20.04
          - windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Alire
      uses: alire-project/setup-alire@v3

    - name: Show data
      shell: bash
      run: |
        set -v
        alr show
        cat mocklib/alire.toml
        alr printenv | grep OK
